export const PATH = {
  LOGIN: '/login',
  SIGNUP: '/signup',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset',
  MAGIC_LINK_LOGIN: '/login/magic-link',
  HOME: '/',
  DASHBOARD: '/dashboard',
  VAULTS: '/dashboard/vaults',
  VAULT_DETAIL: '/dashboard/vaults/:vaultId',
  AUDIT_LOG: '/dashboard/audit-log',
  API_KEYS: '/dashboard/api-keys',
  FEATURES: '/features',
  ABOUT: '/about',
  DOCS: '/docs',
  MOCK: '/mock',
  USERS: '/users/:name',
};
